# Generated by Django 6.0.2 on 2026-06-21 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-published_date'], 'permissions': (('blog.create_post', 'Post created'), ('blog.change_post', 'Post updated'), ('blog.delete_post', 'Post deleted'))},
        ),
    ]
